server:
    port: 8081
spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
          ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/shopping?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration


